---
config:
  theme: neo
---
timeline
    title Kế Hoạch Đào Tạo
    2025 - 2026 HK1 : IE005 (Giới Thiệu Ngành CNTT)
        : IT007 (Hệ Điều Hành)
        : MA003 (Đại Số Tuyến Tính)
        : IE101 (Cơ Sở Hạ Tầng CNTT)
        : IE103 (Quản Lý Thông Tin)
    2025 - 2026 HK2 : IT003 (Cấu Trúc Dữ Liệu và Giải Thuật)
         : MA004 (Cấu Trúc Rời Rạc)
         : MA005 (Xác Suất Thống Kê)
         : IE105 (Nhập Môn Bảo Đảm và An Ninh Thông Tin)
    2025 - 2026 HK3 : Các Môn Chuyên Ngành
        : Chuyên Đề Tốt Nghiệp
    2025 - 2026 HK4 : IE505 (Khóa Luận Tốt Nghiệp)
        : IE501 (Đồ Án Tốt Nghiệp)
        : Hoặc IE502 (Đồ Án Tốt Nghiệp tại Doanh Nghiệp)
